apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bumpy-llama
  name: bumpy-llama
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - if [ -f /workdir/eager.txt ]; then sleep 1000000; else exit 1; fi
    image: alpine
    name: bumpy-llama
    volumeMounts:
    - name: shared-volume
      mountPath: /workdir

  initContainers:
  - name: example
    image: busybox
    args:
    - /bin/sh
    - -c
    - 'touch  /workdir/eager.txt'
    volumeMounts:
    - name: shared-volume
      mountPath: /workdir

  volumes:
  - name: shared-volume
    emptyDir: {}
