apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kuuc8
  name: kuuc8
spec:
  containers:
  - image: nginx
    name: kuuc8
  - image: redis
    name: redis
  - image: memcached
    name: memcached
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
