apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-kusc00101
  name: nginx-kusc00101
spec:
  nodeSelector:
    disk: spinning
  containers:
  - image: nginx
    name: nginx-kusc00101
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
