apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-secrets-via-env
  name: pod-secrets-via-env
spec:
  containers:
  - env:
    - name: CREDENTIALS
      valueFrom:
        secretKeyRef:
          name: super-secret
          key: super-secret 
    image: redis
    name: pod-secrets-via-env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
